'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('mentisAPI', {
  listConversations: () => ipcRenderer.invoke('mentis:list-conversations'),
  openConversation: (id, flags) => ipcRenderer.invoke('mentis:open-conversation', { id, flags }),
  sendMessage: (message) => ipcRenderer.invoke('mentis:send-message', message),
  stopTurn: () => ipcRenderer.invoke('mentis:stop-turn'),
  onLog: (callback) => ipcRenderer.on('mentis:log', (_event, line) => callback(line)),
  onHistoryUpdated: (callback) => ipcRenderer.on('mentis:history-updated', (_event, entries) => callback(entries)),
  onTurnComplete: (callback) => ipcRenderer.on('mentis:turn-complete', () => callback()),
  onTurnError: (callback) => ipcRenderer.on('mentis:turn-error', (_event, payload) => callback(payload)),
  onLivePreview: (callback) => ipcRenderer.on('mentis:live-preview', (_event, imgPath) => callback(imgPath)),
  // Trozos de la respuesta final a medida que el modelo la escribe (ver NVANSWER en nv_stream.py).
  onAnswerChunk: (callback) => ipcRenderer.on('mentis:answer-chunk', (_event, texto) => callback(texto)),
  listFolders: () => ipcRenderer.invoke('mentis:list-folders'),
  createFolder: (name) => ipcRenderer.invoke('mentis:create-folder', name),
  renameFolder: (id, name) => ipcRenderer.invoke('mentis:rename-folder', { id, name }),
  deleteFolder: (id) => ipcRenderer.invoke('mentis:delete-folder', id),
  assignFolder: (convId, folderId) => ipcRenderer.invoke('mentis:assign-folder', { convId, folderId }),
  pickAttachment: () => ipcRenderer.invoke('mentis:pick-attachment'),
  getWorkspaceRoot: () => ipcRenderer.invoke('mentis:get-workspace-root'),
  readWorkspaceFile: (relPath) => ipcRenderer.invoke('mentis:read-workspace-file', relPath),
  pickCapability: () => ipcRenderer.invoke('mentis:pick-capability'),
  createCapability: (payload) => ipcRenderer.invoke('mentis:create-capability', payload),
  listCapabilities: () => ipcRenderer.invoke('mentis:list-capabilities'),
  connectorStatus: () => ipcRenderer.invoke('mentis:connector-status'),
  listMcpConnectors: () => ipcRenderer.invoke('mentis:list-mcp-connectors'),
  toggleMcpConnector: (name, enabled) => ipcRenderer.invoke('mentis:toggle-mcp-connector', { name, enabled }),
  toggleConnector: (id, enabled) => ipcRenderer.invoke('mentis:toggle-connector', { id, enabled }),
  listAllConnectors: () => ipcRenderer.invoke('mentis:list-all-connectors'),
  getRunwayStatus: () => ipcRenderer.invoke('mentis:get-runway-status'),
  saveRunwayKey: (apiKey) => ipcRenderer.invoke('mentis:save-runway-key', apiKey),
  removeRunwayKey: () => ipcRenderer.invoke('mentis:remove-runway-key'),
  listProjects: () => ipcRenderer.invoke('mentis:list-projects'),
  createProject: (name) => ipcRenderer.invoke('mentis:create-project', name),
  deleteProject: (id) => ipcRenderer.invoke('mentis:delete-project', id),
  listProjectConversations: (projectId) => ipcRenderer.invoke('mentis:list-project-conversations', projectId),
  createProjectConversation: (projectId) => ipcRenderer.invoke('mentis:create-project-conversation', projectId),
  projectForConversation: (conversationId) => ipcRenderer.invoke('mentis:project-for-conversation', conversationId),
  getSettings: () => ipcRenderer.invoke('mentis:get-settings'),
  saveVoz: (fields) => ipcRenderer.invoke('mentis:save-voz', fields),
  ventana: (accion) => ipcRenderer.invoke('mentis:ventana', accion),
  saveCustomModel: (payload) => ipcRenderer.invoke('mentis:save-custom-model', payload),
  removeCustomModel: (role) => ipcRenderer.invoke('mentis:remove-custom-model', role),
  getIdeogramStatus: () => ipcRenderer.invoke('mentis:get-ideogram-status'),
  saveIdeogramKey: (apiKey) => ipcRenderer.invoke('mentis:save-ideogram-key', apiKey),
  removeIdeogramKey: () => ipcRenderer.invoke('mentis:remove-ideogram-key'),
  saveProfile: (fields) => ipcRenderer.invoke('mentis:save-profile', fields),
  // Paleta y nombre de la IA (ver settings-store.getApariencia).
  saveApariencia: (fields) => ipcRenderer.invoke('mentis:save-apariencia', fields),
  // Idiomas: en cual te escribe (lectura) y en cual te habla y te entiende (habla).
  idiomasDisponibles: () => ipcRenderer.invoke('mentis:idiomas-disponibles'),
  getIdioma: () => ipcRenderer.invoke('mentis:get-idioma'),
  saveIdioma: (fields) => ipcRenderer.invoke('mentis:save-idioma', fields),
  // Modos: Mentis / Code / Designe / Cowork (ver modos.json).
  // El tema decide que logo se ve; el icono de la ventana y el de la bandeja los pinta
  // Windows, no el CSS, asi que hay que avisarle al proceso principal.
  setLogo: (variante) => ipcRenderer.invoke('mentis:set-logo', variante),
  modosLista: () => ipcRenderer.invoke('mentis:modos-lista'),
  modoActual: () => ipcRenderer.invoke('mentis:modo-actual'),
  setModo: (id) => ipcRenderer.invoke('mentis:set-modo', id),
  // El aviso va por evento y no como respuesta del setModo a proposito: asi la ventana se entera
  // aunque el cambio venga de otro lado (un atajo, la pagina del celular, un script), y no solo
  // cuando lo apreto el propio boton.
  onModoCambio: (cb) => ipcRenderer.on('mentis:modo-cambio', (_e, modo) => cb(modo)),
  // Modo administrador: sólo hace algo en la máquina que tiene la clave privada de firma.
  esAdministrador: () => ipcRenderer.invoke('mentis:es-administrador'),
  estadoPublicacion: () => ipcRenderer.invoke('mentis:estado-publicacion'),
  publicarRevisar: () => ipcRenderer.invoke('mentis:publicar-revisar'),
  publicar: (notas) => ipcRenderer.invoke('mentis:publicar', notas),
  publicarRetirar: () => ipcRenderer.invoke('mentis:publicar-retirar'),
  saveUserMemory: (text) => ipcRenderer.invoke('mentis:save-user-memory', text),
  saveSelfMemory: (text) => ipcRenderer.invoke('mentis:save-self-memory', text),
  pickAvatar: () => ipcRenderer.invoke('mentis:pick-avatar'),
  onboardingStatus: () => ipcRenderer.invoke('mentis:onboarding-status'),
  markOnboardingDone: () => ipcRenderer.invoke('mentis:mark-onboarding-done'),
  openArtifact: (artifact) => ipcRenderer.invoke('mentis:open-artifact', artifact),
  // Ver adentro de la app en vez de abrir una app de Windows (2026-08-12). 'verArtefacto' trae el
  // contenido para dibujarlo acá; 'listarCreaciones' es la galería de todo lo que Mentis hizo.
  verArtefacto: (artifact) => ipcRenderer.invoke('mentis:ver-artefacto', artifact),
  listarCreaciones: (modo) => ipcRenderer.invoke('mentis:listar-creaciones', modo),
  anotarCreacion: (ruta, modo) => ipcRenderer.invoke('mentis:anotar-creacion', ruta, modo),
  forceStop: () => ipcRenderer.invoke('mentis:force-stop'),
  transcribeAudio: (buffer) => ipcRenderer.invoke('mentis:transcribe-audio', buffer),
  tts: (texto) => ipcRenderer.invoke('mentis:tts', texto),
  getUsageStats: () => ipcRenderer.invoke('mentis:get-usage-stats'),
  getUsageCosts: () => ipcRenderer.invoke('mentis:get-usage-costs'),
  searchConversations: (query) => ipcRenderer.invoke('mentis:search-conversations', query),
  listScheduledTasks: () => ipcRenderer.invoke('mentis:list-scheduled-tasks'),
  createScheduledTask: (payload) => ipcRenderer.invoke('mentis:create-scheduled-task', payload),
  updateScheduledTask: (id, patch) => ipcRenderer.invoke('mentis:update-scheduled-task', { id, patch }),
  deleteScheduledTask: (id) => ipcRenderer.invoke('mentis:delete-scheduled-task', id),
  onScheduledTaskRan: (callback) => ipcRenderer.on('mentis:scheduled-task-ran', (_event, payload) => callback(payload)),
  createBranch: (conversationId, index) => ipcRenderer.invoke('mentis:create-branch', { conversationId, index }),
  getBranchSiblings: (conversationId) => ipcRenderer.invoke('mentis:get-branch-siblings', conversationId),
  exportBackup: () => ipcRenderer.invoke('mentis:export-backup'),
  summarizeAndHandoff: (conversationId) => ipcRenderer.invoke('mentis:summarize-and-handoff', conversationId),
  getLocationWeather: () => ipcRenderer.invoke('mentis:get-location-weather'),
  onReplayGreeting: (callback) => ipcRenderer.on('mentis:replay-greeting', () => callback())
});
